project_id = "jjhwqwxmwygqoqsqrxnf"

[functions.create-checkout-session]
verify_jwt = true

[functions.customer-portal]  
verify_jwt = true

[functions.certificate-issuance]
verify_jwt = true

[functions.refresher-scheduling]
verify_jwt = true

[functions.expiry-reminders]
verify_jwt = true

[functions.generate-certificate-pdf]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.send-user-invitation]
verify_jwt = true