version: '3.8'

services:
  # SkillBridge web application
  skillbridge-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skillbridge-web
    ports:
      - "3000:80"
    environment:
      # These will be loaded from .env file
      - ORG_ID=${ORG_ID}
      - ORG_NAME=${ORG_NAME}
      - ORG_SLUG=${ORG_SLUG}
      - ORG_CONTACT_EMAIL=${ORG_CONTACT_EMAIL}
      - ORG_LOGO_URL=${ORG_LOGO_URL}
      - ORG_PRIMARY_COLOR=${ORG_PRIMARY_COLOR}
      - APP_URL=${APP_URL}
      - APP_DOMAIN=${APP_DOMAIN}
      - SMTP_FROM=${SMTP_FROM}
      - SUPPORT_EMAIL=${SUPPORT_EMAIL}
      - SUBSCRIPTION_PLAN=${SUBSCRIPTION_PLAN}
      - MAX_USERS=${MAX_USERS}
      - SINGLE_TENANT_STRICT=${SINGLE_TENANT_STRICT}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP}
      - DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
      - DEFAULT_ADMIN_FIRST_NAME=${DEFAULT_ADMIN_FIRST_NAME}
      - DEFAULT_ADMIN_LAST_NAME=${DEFAULT_ADMIN_LAST_NAME}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - skillbridge-network

  # Optional: Local PostgreSQL (if not using Supabase)
  # skillbridge-db:
  #   image: postgres:15-alpine
  #   container_name: skillbridge-db
  #   environment:
  #     POSTGRES_DB: skillbridge
  #     POSTGRES_USER: skillbridge
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-skillbridge_password}
  #   volumes:
  #     - skillbridge-db-data:/var/lib/postgresql/data
  #     - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped
  #   networks:
  #     - skillbridge-network

  # Optional: Redis for caching
  # skillbridge-redis:
  #   image: redis:7-alpine
  #   container_name: skillbridge-redis
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
  #   networks:
  #     - skillbridge-network

  # Optional: Nginx reverse proxy (if you need SSL termination)
  # skillbridge-proxy:
  #   image: nginx:alpine
  #   container_name: skillbridge-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/ssl:/etc/nginx/ssl
  #   depends_on:
  #     - skillbridge-web
  #   restart: unless-stopped
  #   networks:
  #     - skillbridge-network

networks:
  skillbridge-network:
    driver: bridge

volumes:
  skillbridge-db-data:
    driver: local