// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjhwqwxmwygqoqsqrxnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqaHdxd3htd3lncW9xc3FyeG5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMTUxNDksImV4cCI6MjA2OTc5MTE0OX0.fiGMKgW391L_YAieqCphQZf9dFA9uBMXyoytsqFfW4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});